  var WOMT_aParteienBeschreibung                 = new Array();
  var WOMT_aParteienBeschreibungChecksum         = new Array();
  var WOMT_sGenerationTimeParteienBeschreibung   = '';
  

/*
  --------------------------------------------------------------
  Vordefinieren der in den Templates gefunden assoziativen Keys
  mit denenen auf WOMT_aTexte und WOMT_aBilder zugriffen wird
  nicht vorhanden Indexe fuehren in Javascript sonst zu Fehlern!

  Wenn mit Variablen auf die assoziativen Arrays zugegriffen wird
  kann dies nicht automatisch analsysit werden,
  die Variablen werden aber zur Erinnuner im output angezeigt!
  --------------------------------------------------------------
*/
WOMT_aParteienBeschreibung[0]=new Array();
WOMT_aParteienBeschreibung[1]=new Array();
WOMT_aParteienBeschreibung[2]=new Array();
WOMT_aParteienBeschreibung[3]=new Array();
WOMT_aParteienBeschreibung[4]=new Array();
WOMT_aParteienBeschreibung[5]=new Array();
WOMT_aParteienBeschreibung[6]=new Array();
WOMT_aParteienBeschreibung[7]=new Array();
WOMT_aParteienBeschreibung[8]=new Array();
WOMT_aParteienBeschreibung[9]=new Array();
WOMT_aParteienBeschreibung[10]=new Array();
WOMT_aParteienBeschreibung[11]=new Array();
WOMT_aParteienBeschreibung[12]=new Array();
WOMT_aParteienBeschreibung[13]=new Array();
WOMT_aParteienBeschreibung[14]=new Array();
WOMT_aParteienBeschreibung[15]=new Array();
WOMT_aParteienBeschreibung[16]=new Array();
WOMT_aParteienBeschreibung[17]=new Array();
WOMT_aParteienBeschreibung[18]=new Array();
WOMT_aParteienBeschreibung[19]=new Array();
WOMT_aParteienBeschreibung[20]=new Array();
WOMT_aParteienBeschreibung[21]=new Array();
WOMT_aParteienBeschreibung[22]=new Array();
WOMT_aParteienBeschreibung[23]=new Array();
WOMT_aParteienBeschreibung[24]=new Array();
WOMT_aParteienBeschreibung[0][0]='Die Grundausrichtung der CDU kombiniert sozialpolitischen christlichen Konservatismus mit einer ökonomisch marktwirtschaftlichen Orientierung. Sie steht für eine weitere Vertiefung der europäischen Integration, eine Vergemeinschaftung von Schulden lehnt sie jedoch ab.';
WOMT_aParteienBeschreibung[1][0]='Die SPD verbindet programmatisch die Garantie von Freiheits- und Grundrechten mit sozialer Sicherung durch staatliche Maßnahmen. In der Europapolitik fordert sie unter anderem eine Bankenunion, eine europäische Finanztransaktionssteuer und EU-weite soziale Mindeststandards.';
WOMT_aParteienBeschreibung[2][0]='Kernthemen der GRÜNEN sind Umwelt, Energie und Bürgerrechte. Eine einseitige Sparpolitik in der EU lehnt die Partei ab und fordert stattdessen Investitionsprogramme. Sie spricht sich dafür aus, Flüchtlingen in der EU Asyl zu gewähren und weiteren Staaten eine Beitrittsperspektive zu geben.';
WOMT_aParteienBeschreibung[3][0]='Die FDP versteht sich als liberale Partei und Befürworterin der europäischen Integration. Sie lehnt Vorratsdatenspeicherung ab und fordert ein Spionageverbot innerhalb der EU. Die FDP fordert mehr Kompetenzen für das EU-Parlament, lehnt aber die Vergemeinschaftung von Staatsschulden ab.';
WOMT_aParteienBeschreibung[4][0]='DIE LINKE tritt für eine Veränderung des Wirtschafts- und Gesellschaftssystems hin zum demokratischen Sozialismus ein. Im Mittelpunkt der programmatischen Aussagen stehen die soziale Umverteilung - etwa durch Mindestlöhne - und der Kampf gegen die "Militarisierung" der EU.';
WOMT_aParteienBeschreibung[5][0]='Die CSU ist die bayerische Schwesterpartei der CDU. Die Partei ist pro-europäisch, kritisiert jedoch, dass in der EU zu viel zentral geregelt würde. Sie spricht sich für Volksabstimmungen bei zentralen Fragen der Europapolitik aus.';
WOMT_aParteienBeschreibung[6][0]='Die FREIEN WÄHLER sind aus kommunalpolitisch aktiven Wählergemeinschaften, Bündnissen und Initiativen entstanden. Die Partei setzt vor allem auf das Subsidiaritätsprinzip. Sie fordert europäische Volksentscheide und die Stärkung des "Ausschusses der Regionen".';
WOMT_aParteienBeschreibung[7][0]='Die Partei der Humanisten beruft sich mit ihrer Politik auf den Evolutionären Humanismus. Auf ihrer Website bezeichnet sie sich als die „rational-liberale Partei der Moderne“. Was genau sie damit meint, umschreibt sie folgendermaßen: „Wir trauen und muten dem Menschen seine Selbstverwirklichung in größtmöglicher Freiheit und persönlicher Verantwortung zu. Wir setzen uns uneingeschränkt für zivilisatorischen und technologischen Fortschritt ein. Rationale, erkenntnisgeleitete Entscheidungsfindung ist dafür unabdingbar – Fakten gehen immer vor Befindlichkeit.“';
WOMT_aParteienBeschreibung[8][0]='Das Kernanliegen der Tierschutzpartei ist ein konsequenter Umwelt- und Tierschutz, etwa durch die Aufnahme von Grundrechten für Tiere in Grundgesetz und europäische Verträge. Auf europäischer Ebene setzt sie sich für eine Reduzierung der Produktion von tierischen Lebensmitteln ein.';
WOMT_aParteienBeschreibung[9][0]='Die Partei FAMILIE versteht ihr zentrales Politikfeld  die Familienpolitik - als gesamtgesellschaftliche Aufgabe. Eine Kernforderung der Partei ist die Gleichstellung von Familien- und Erwerbsarbeit. In der EU möchte sie "Familiengerechtigkeit" herstellen.';
WOMT_aParteienBeschreibung[10][0]='Die programmatischen Schwerpunkte der PIRATEN liegen in den Themen Netzpolitik, Bürgerrechte, Transparenz und Informationsfreiheit. Sie befürworten die europäische Integration klar. Der Einfluss des Europäischen Parlaments und der Bürger soll nach ihrem Willen in der EU gestärkt werden.';
WOMT_aParteienBeschreibung[11][0]='Die ÖDP ist aus der Umweltschutzbewegung der 1970er- und 1980er-Jahre entstanden. Sie spricht sich für eine ökologische Landwirtschaft mit weitgehend dezentraler Vermarktung aus. Neben ökologischen Themen ist die Einführung von Volksentscheiden Kernanliegen der Partei.';
WOMT_aParteienBeschreibung[12][0]='Volt Europa (üblicherweise abgekürzt Volt) ist eine pro-europäische Bürgerbewegung und pan-europäische Kleinpartei. Sie wurde 2017 von Andrea Venzon, Colombe Cahen-Salvador und Damian Freiherr von Boeselager gegründet. Die Organisation verfolgt in vielen Politikfeldern, wie Klimawandel, Migration, ökonomischer Ungleichheit, internationalen Konflikten, Terrorismus und dem Einfluss der technologischen Revolution auf den Arbeitsmarkt, einen europäischen Ansatz.';
WOMT_aParteienBeschreibung[13][0]='Die Partei Volksabstimmung ist national-konservativ orientiert. Volksentscheide nach Schweizer Vorbild sind das Ziel der Partei, Europaskepsis wichtiger Bestandteil der programmatischen Ausrichtung. U. a. fordert sie die Rückkehr zur D-Mark.';
WOMT_aParteienBeschreibung[14][0]='Die BP sieht sich als Interessenvertretung der gesamten bayerischen Bevölkerung. Sie setzt sich für ein Europa der Regionen ein, das stärker föderal geprägt ist. Familienpolitisch steht die Partei für eine Verschärfung des Abtreibungsrechts und die Einführung eines Erziehungsgehalts.';
WOMT_aParteienBeschreibung[15][0]='Die Sozialistische Gleichheitspartei (SGP), Vierte Internationale (1971 bis 1997 Bund Sozialistischer Arbeiter; BSA, 1997 bis Februar 2017 Partei für Soziale Gleichheit, PSG), ist eine deutsche trotzkistische Kleinpartei. Sie sieht sich in der Kontinuität zu Karl Marx, Friedrich Engels, Wladimir Iljitsch Lenin, Leo Trotzki und Rosa Luxemburg und ist die deutsche Sektion des Internationalen Komitees der Vierten Internationale (IKVI). Sie wird vom Verfassungsschutz beobachtet und von diesem als linksextremistisch eingestuft.';
WOMT_aParteienBeschreibung[16][0]='Aktion Partei für Tierschutz – DAS ORIGINAL (TIERSCHUTZ hier!), ';
WOMT_aParteienBeschreibung[17][0]='Die DKP ist nach eigener Beschreibung eine marxistische Partei und kritisch gegenüber der EU eingestellt, da diese nicht die Interessen der Bürger vertrete. Programmatisch fordert die Partei einen Schuldenschnitt für die finanzschwachen Mitgliedsstaaten und einen EU-weiten Mindestlohn.';
WOMT_aParteienBeschreibung[18][0]='Die BüSo fordert die Abkehr vom Vertrag von Lissabon und die Rückkehr zur D-Mark. Die Partei warnt vor einem Zusammenbruch des Finanzsystems und befürwortet eine neue Weltwirtschaftsordnung. Die BüSo unterstützt die Atomkraft als ökologische Energiequelle.';
WOMT_aParteienBeschreibung[19][0]='Die Allianz für Menschenrechte, Tier- und Naturschutz (Tierschutzallianz) ist eine Partei, die sich im November 2013 als Abspaltung der Tierschutzpartei gründete. Nach eigenen Angaben war der Grund hierfür die nicht ausreichende Abgrenzung der Tierschutzpartei vom rechten Spektrum.';
WOMT_aParteienBeschreibung[20][0]='Kritik an der EU ist das Leitthema der AfD. Den Euro hält die Partei für schädlich, die Institutionen der EU für undemokratisch. Die AfD kritisiert zudem in besonderem Maße die Zuwanderungspolitik in der EU und lehnt jede Form der Vergemeinschaftung von Staatsschulden ab.';
WOMT_aParteienBeschreibung[21][0]='Bündnis C – Christen für Deutschland ist eine Kleinpartei in Deutschland und richtet ihre Politik am christlichen Menschenbild aus. Bündnis C wurde im Jahr 2015 durch die Fusion der christlich-fundamentalistischen Parteien Partei Bibeltreuer Christen und AUF – Partei für Arbeit, Umwelt und Familie gegründet.';
WOMT_aParteienBeschreibung[22][0]='Erklärtes Ziel der MLPD ist eine "klassenlose kommunistische Gesellschaft". Zur Europawahl tritt sie mit dem Slogan "Rebellion gegen die EU ist gerechtfertigt!" an. Konkret fordert die MLPD ein uneingeschränktes Asylrecht und die "Rettung der Umwelt vor der Profitwirtschaft".';
WOMT_aParteienBeschreibung[23][0]='Die NPD ist eine rechtsextreme Partei. Die Ablehnung von Zuwanderung und die "Verteidigung der ethno-kulturellen Identität" sind zentraler Bestandteil ihrer Programmatik. Sie fordert die Rückkehr zur D-Mark, allgemeine Grenzkontrollen innerhalb der EU und den Ausstieg aus allen Rettungspaketen.';
WOMT_aParteienBeschreibung[24][0]='Die Partei Die PARTEI ist eng mit dem Satire-Magazin Titanic verbunden. Die Ernsthaftigkeit ihrer Forderungen - Abschaffung der Sommerzeit, Bau einer Mauer um Deutschland herum sowie eine "Faulenquote" - wird immer wieder in Frage gestellt.';
WOMT_aParteienBeschreibung[25][0]='Das Bündnis für Innovation und Gerechtigkeit (BIG) ist eine 2010 in Köln gegründete deutsche Kleinpartei. Sie ist eine der ersten von Muslimen gegründeten Parteien Deutschlands und beabsichtigt, sich insbesondere für die Interessen von Migranten und deren gesellschaftlicher Integration in Deutschland einzusetzen.';
WOMT_aParteienBeschreibung[26][0]='Das Bündnis Grundeinkommen (BGE), ist eine monothematische deutsche Kleinpartei, die im Programm und in ihrer Satzung für die Einführung des bedingungslosen Grundeinkommens in Deutschland eintritt.';
WOMT_aParteienBeschreibung[27][0]='Demokratie Direkt (DIE DIREKTE!), Basis für die Parteigründung war eine studentische Initiative mit dem Ziel die Demokratie lebendiger zu gestalten und ein neues demokratisches Konzept zu entwickeln.';
WOMT_aParteienBeschreibung[28][0]='Democracy in Europe Movement 2025 (kurz DiEM25, deutsch Bewegung Demokratie in Europa 2025) ist eine linke paneuropäische Bewegung, die nach eigenen Angaben die „gerechte Gestaltung des 21. Jahrhunderts“ zum Ziel hat. Die Bewegung ist Teil der weltweit angelegten Progressiven Internationalen, der auch die Bewegung um Bernie Sanders angehört.';
WOMT_aParteienBeschreibung[29][0]='Der III. Weg (auch: Der Dritte Weg) ist eine rechtsextreme neonazistische Kleinpartei in Deutschland. Sie wurde am 28. September 2013 unter maßgeblicher Beteiligung ehemaliger NPD-Funktionäre und Aktivisten des im Juli 2014 verbotenen Freien Netzes Süd (FNS) gegründet. Sie gilt als Versuch, das FNS unter dem Schutz des Parteienprivilegs weiterzuführen.';
WOMT_aParteienBeschreibung[30][0]='Die Grauen – Für alle Generationen sieht sich in der Tradition der ehemaligen Bewegung Graue Panther. Im Gegensatz zu dieser sieht sich die Partei nicht als Seniorenpartei, sondern verfolgt einen generationenübergreifenden politischen Ansatz, der auch im Namenszusatz „Für alle Generationen“ zum Ausdruck kommen soll. In der Präambel ihres Parteiprogrammes formuliert die Partei ihre Philosophie:„In einer sich immer schneller bewegenden, globalisierten Welt wollen die Grauen die Tatkraft der Jugend mit der Erfahrung der Älteren verbinden, um gemeinsam eine lebenswerte Gesellschaft zu formen.“';
WOMT_aParteienBeschreibung[31][0]='DIE RECHTE – Partei für Volksabstimmung, Souveränität und Heimatschutz ist eine rechtsextreme, neonazistische Kleinpartei in Deutschland. An der Gründung der Partei am 27. Mai 2012 waren hauptsächlich ehemalige Mitglieder der inzwischen aufgelösten rechtsextremen Deutschen Volksunion, die im Mai 2012 mit der NPD fusioniert hatte, beteiligt.';
WOMT_aParteienBeschreibung[32][0]='Die Violetten: Die Partei vertritt nach eigenen Angaben „alternative spirituelle Politik im neuen Zeitalter“ und sieht sich als Vertreterin spiritueller Menschen, die ihrer Weltsicht in der Politik Geltung verschaffen möchten. „Spiritualität“ nehme einen zentralen Platz in der Anschauung und dem Programm ein. Inhaltlich konzentriert sich die Partei auf innenpolitische Themen, insbesondere in den Bereichen Bildung und Erziehung, Wirtschaft und Finanzen sowie Arbeit und Umwelt.';
WOMT_aParteienBeschreibung[33][0]='Die Europäische Partei Liebe (LIEBE): Die Liebe ist stärker als das Böse und die Liebe muss die Welt regieren! Die Partei leitet verschiedene Forderungen daraus ab, dass „alle Menschen das gleiche Recht auf Gerechtigkeit, Gleichheit Würde und Liebe haben“.';
WOMT_aParteienBeschreibung[34][0]='Die Feministische Partei Die Frauen (DIE FRAUEN): Die Partei stellt laut eigener Aussage die Sichtweise von Frauen in den Mittelpunkt ihrer Politik. Selbsterklärtes Ziel der Partei ist die Gestaltung einer herrschaftsfreien Gesellschaft, in der nicht auf Kosten von Frauen, anderer Völker oder der Natur gelebt wird, sowie eine Gesellschaft, in der für alle Personen, unabhängig von ihrem Geschlecht, ihrer Herkunft, ihrer Nationalität gleichwertige Lebensbedingungen bestehen.';
WOMT_aParteienBeschreibung[35][0]='Graue Panther (ehemals: Allianz Graue Panther Deutschland) ist eine deutsche Kleinpartei. Sie entstand aus einer Fusion der Partei Graue Panther Deutschland, die bereits am 14. April 2012 mit der Partei Die Grauen – Generationspartei fusioniert war, und der Partei Allianz Graue Panther. All diese Parteien entstanden aus der 2008 aufgelösten Partei Die Grauen – Graue Panther.';
WOMT_aParteienBeschreibung[36][0]='LKR, Zusatzbezeichnung Bernd Lucke und die Liberal-Konservativen Reformer: In ihrer Satzung bekennen sich die Liberal-Konservativen Reformer zum freiheitlichen, demokratischen und sozialen Rechtsstaat sowie den im Grundgesetz verbrieften Grundrechten. In der Satzung wird die Ablehnung „ausländerfeindlicher, rassistischer, nationalistischer, antisemitischer, islamfeindlicher, islamistischer, homophober, rechts- oder linksradikaler Positionen sowie aller Parteien, Organisationen und Medien, welche solche Positionen vertreten oder ihnen Raum geben“ formuliert.';
WOMT_aParteienBeschreibung[37][0]='Menschliche Welt (Zusatzbezeichnung: für das Wohl und Glücklichsein aller, Kurzbezeichnung: MENSCHLICHE WELT) ist eine deutsche politische Partei. Sie wurde 2013 mit dem Willen gegründet, auf die Bildung einer globalen menschlichen Gesellschaft hin zu wirken. Eine Voraussetzung für eine menschliche Gesellschaft sieht die Partei in einer allumfassend wohlwollenden Denk- und Handlungsweise der Führenden. Darum ist es ein Hauptanliegen von Menschliche Welt, Menschen dabei zu unterstützen, altruistische Handlungsweisen und Führungskompetenzen zu entwickeln.';
WOMT_aParteienBeschreibung[38][0]='Neue Liberale – Die Sozialliberalen (NL): In Dokumenten des Gründungskreises heißt es, Ziel sei „eine freie Gesellschaft, in der jeder Mensch in seiner Individualität geachtet wird und sich entfalten kann“. Zentrale Themen der Neuen Liberalen sind die mögliche Einführung eines Bürgergelds sowie die Verbesserung der Chancen für „Flüchtlinge, Migranten, Menschen mit Behinderungen, alte Menschen, zunehmend auch Familien, aber auch Berufsstarter“.';
WOMT_aParteienBeschreibung[39][0]='Die Ökologische Linke (ÖkoLinX; früher ÖkoLi) ist eine deutsche Kleinpartei, die im Bündnis mit außerparlamentarischen sozialen Bewegungen einen basisdemokratischen Ökosozialismus anstrebt. Bekannte Gründungsmitglieder sind Jutta Ditfurth und Manfred Zieran.';
WOMT_aParteienBeschreibung[40][0]='Partei für die Tiere';
WOMT_aParteienBeschreibung[41][0]='Die Partei für Gesundheitsforschung (Kurzbezeichnung: Gesundheitsforschung) ist eine politische Partei in Deutschland. Als Ein-Themen-Partei widmet sie sich ausschließlich dem Einsatz für eine schnellere Entwicklung wirksamer Medizin gegen Alterskrankheiten wie Krebs, Alzheimer, Herzinfarkt, Schlaganfall, Diabetes Typ 2, Makuladegeneration, Arthrose, Osteoporose und Parkinson. Forschungsmittel in anderen medizinischen Bereichen sollten nicht gekürzt werden und indirekt durch die Nutzung neuer wissenschaftlicher Erkenntnisse profitieren. Neben einer Verbesserung der öffentlichen Gesundheit wird auch ein hoher wirtschaftlicher Gewinn erwartet.';
WOMT_aParteienBeschreibungChecksum["sum"]='f3d2e216c1752030cf39678dbe1e23af';
WOMT_aParteienBeschreibungChecksum["sum2"]='6bd5e9d1cee32b2e9ffdba6429e8129b';
WOMT_sGenerationTimeParteienBeschreibung ='24.04.2014 13:49:51';
